### ISSUE TITLE
"_OBJC_CLASS_$_RNWatch", referenced from:

### ISSUE THREAD

**Issue by khl3o** [AlexisLeon/react-native-watch#2]
I have the following error:

![capture d ecran 2018-03-25 a 01 18 19](https://user-images.githubusercontent.com/3739063/37870308-ae19fae0-2fca-11e8-9349-efa83b706928.png)

Is it because I wrote my watchApp in swift ?

**Comment by AlexisLeon** [comment]
Try:
Clean build: `cmd + K`
Go to `Build Settings` -> `Other Linker Flags`. Add `-ObjC` in debug mode.

**Comment by khl3o** [comment]
The clean build fixed my problem.
Do you have any ressources to know how to implement it from react-native side ?

**Comment by AlexisLeon** [comment]
To install the module follow the instructions in [Getting Started](https://github.com/AlexisLeon/react-native-watch/blob/master/README.md#getting-started) section.

To implement the lib in JS read the [Usage](https://github.com/AlexisLeon/react-native-watch/blob/master/README.md#usage) section.
